modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="snowrealmagic"
version="${file.jarVersion}"
displayName="Snow Real Magic Potato Edition"
authors="Snownee, TeamPotato"
description="Tweak vanilla snow layer."

[[dependencies.snowrealmagic]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.4, 3.10)"
    ordering="BEFORE"
    side="BOTH"

[modproperties.snowrealmagic]
    catalogueItemIcon="minecraft:snow_block" #Support for Catalogue mod
